name: branta
description: A Branta SDK for Dart.
version: 0.0.1
repository: https://github.com/BrantaOps/branta-dart

environment:
  sdk: ^3.10.4

dependencies:
  crypto: ^3.0.7
  cryptography: ^2.9.0
  dotenv: ^4.2.0
  http: ^1.6.0
  json_annotation: ^4.9.0
  json_serializable: ^6.11.3
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^6.0.0
  test: ^1.25.6
